language: c

env:
  - R_PKG="$(basename $TRAVIS_REPO_SLUG)"

install:
  - sudo apt-add-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu `lsb_release -cs`/"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo apt-get update -qq
  - sudo apt-get install -qq r-base-core
  - "wget -q -O - http://yihui.name/xran/r-config | bash"

script:
  - cd ..; rm -f *.tar.gz; R CMD build $R_PKG
  - R CMD check ${R_PKG}_*.tar.gz --no-manual
  - cd $R_PKG

# deploy to XRAN
after_success:
  - set -e
  - "(wget -q -O - http://yihui.name/xran/r-xran | bash)"

after_failure:
  - cd ..; for i in `ls *.Rcheck/00*`; do cat $i; done
